name: Deploy Docs

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    environment: github-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: lambda
      - uses: vlang/setup-v@v1

      - name: Generate docs
        run: |
          pushd lambda
          v doc -readme -m -f html .
          popd

      - uses: actions/upload-pages-artifact@v3
        with:
          path: lambda/_docs/
      - uses: actions/deploy-pages@v4
