name: Deploy Docs

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  deploy:
    environment: github-pages
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vlang/setup-v@v1
      - run: v doc -readme -m -f html .
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _docs/
      - uses: actions/deploy-pages@v4
